# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1512289679);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1512289799);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1512315239);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1512289559);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1512311039);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1512289919);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.dir", "/root/Desktop");
user_pref("browser.download.folderList", 0);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1512309370420");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1512311078420");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1519216458966");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1519220058966");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170221152033");
user_pref("browser.slowStartup.averageTime", 2027);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://google.com/");
user_pref("browser.startup.homepage_override.buildID", "20170221152033");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1512342535594");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1512256336061");
user_pref("datareporting.policy.firstRunTime", "1512256135594");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2315);
user_pref("datareporting.sessions.current.main", 240);
user_pref("datareporting.sessions.current.sessionRestored", 2463);
user_pref("datareporting.sessions.current.startTime", "1519216452690");
user_pref("datareporting.sessions.current.totalTime", 17);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.3", "{\"s\":1513524333062,\"a\":6,\"t\":31,\"c\":false,\"m\":200,\"fp\":1681,\"sr\":1790}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1513612595761,\"a\":2,\"t\":13,\"c\":true,\"m\":1091,\"fp\":3534,\"sr\":4393}");
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1512289680);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1487691275000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1487691275000}}}");
user_pref("font.internaluseonly.changed", true);
user_pref("gecko.buildID", "20170221152033");
user_pref("gecko.mstone", "45.7.0");
user_pref("idle.lastDailyNotification", 1513524422);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1512256388);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170221152033");
user_pref("media.gmp-manager.lastCheck", 1513524396);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 25706);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1519216452);
user_pref("toolkit.telemetry.cachedClientID", "b6932b48-280b-4ab4-a22a-c707adf9ddcf");
user_pref("toolkit.telemetry.previousBuildID", "20170221152033");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
